spring:
  application:
    name: trading-backend
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/tradingdb
    username: ${DB_USERNAME:tradinguser}
    password: ${DB_PASSWORD:tradingpass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  # Redis Configuration (선택사항 - Claude Code와 통신용)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 60000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# API Keys Configuration (기본값: 모의투자)
api:
  kis:
    app-key: PSSnf5wc2GTe5sOBOHt2PJwVppcNPgBwpEhO
    secret-key: 8JPIwpYdZHFVDt00VaZTu3MoLqHCO08bD9eJY4HAhAEqLs84JQoKQVeMBNamBJmPJYk9IMNggq7k3NcMjL28ZAZ99zhby1CDzLQvIK9pHjt+wygTmRUd0VhtRnEO7o+9T/M7MnifSfMiCUvLR9/1oi342pGfUOjipE8vhOxm4XDkhq2kvXQ=
    base-url: https://openapivts.koreainvestment.com:29443  # 모의투자 URL
    account-number: 50153145
    account-product-code: "01"
  
  # Claude API 설정 제거 (Claude Code CLI 사용)
  # claude:
  #   api-key: not_needed
  #   base-url: not_needed
  
  # AI Service 설정 제거 (Claude Code CLI 직접 사용)
  # ai-service:
  #   base-url: not_needed

# Rate Limiting Configuration (KIS API만)
rate-limit:
  kis:
    calls-per-second: 15
    burst-capacity: 20

# Trading Configuration
trading:
  max-position-size: 100000
  max-daily-loss: 50000
  max-portfolio-size: 10
  trading-hours:
    start: "09:00"
    end: "15:30"
  
  risk:
    max-drawdown: 0.15
    stop-loss-percentage: 0.05
    take-profit-percentage: 0.10

# File Monitoring for Claude Code results
file-monitor:
  data-directory: ${user.dir}/../data
  analysis-directory: ${user.dir}/../data/analysis
  signals-directory: ${user.dir}/../data/signals
  reports-directory: ${user.dir}/../data/reports
  poll-interval: 5000  # 5초마다 파일 변경 확인

# Logging Configuration
logging:
  level:
    root: INFO
    com.tokentrader: DEBUG
    com.tokentrader.api.kis: INFO
    org.springframework.web: INFO
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: logs/trading-backend.log
    max-size: 10MB
    max-history: 30

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha

# Development Profile (H2 DB, 모의투자)
---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.tokentrader: DEBUG
    com.tokentrader.api.kis: INFO

# Production Profile (PostgreSQL, 실거래)
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

api:
  kis:
    app-key: ${KIS_REAL_APP_KEY}
    secret-key: ${KIS_REAL_SECRET_KEY}
    base-url: https://openapi.koreainvestment.com:9443  # 실거래 URL
    account-number: ${KIS_REAL_ACCOUNT_NUMBER}
    account-product-code: "01"

logging:
  level:
    root: WARN
    com.tokentrader: INFO

# Test Profile (H2 DB, 모의투자)
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

api:
  kis:
    app-key: ${KIS_MOCK_APP_KEY}
    secret-key: ${KIS_MOCK_SECRET_KEY}
    base-url: https://openapivts.koreainvestment.com:29443  # 모의투자 URL
    account-number: ${KIS_MOCK_ACCOUNT_NUMBER}
    account-product-code: "01"